
# Containers are called services
services:
#Docker builds an image using the Dockerfile inside the frontend folder.
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - frontend-net
   




  backend:
    build: ./backend
    ports:
      - "5000:5000"
      # The backend needs to communicate with the database, so we set environment variables for database connection
    environment:
     DB_HOST: ${DB_HOST}
     DB_PORT: ${DB_PORT}
     DB_NAME: ${DB_NAME}
     DB_USER: ${DB_USER}
     DB_PASSWORD: ${DB_PASSWORD}
      # The backend needs to communicate with the frontend and database 
    networks:
      - db-net
      - frontend-net


           

  db:
  #Docker downloads the official PostgreSQL image from Docker Hub
    image: postgres:15-alpine
    environment:
    #PostgreSQL uses them to create the database and its user
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      #Store all PostgreSQL data in a named volume called postgres-data
    volumes:
       - postgres-data:/var/lib/postgresql/data
    networks:
      - db-net
volumes:
  postgres-data:

# adding two networks to separate frontend and backend communication
networks:
  frontend-net:
  db-net:
